### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by maljoh** [notoriousbdg/vrops-dashboard-rightsizing_details#3]
Hi 

Tried to install this dashboard and i followed the guide perfectly i think :-)
The problem is that i get in internal error when opening dashboard. Im using Vrops 8.1 advanced.

regards
Rasmus
![Github](https://user-images.githubusercontent.com/71315095/93182305-d6f81300-f739-11ea-98d3-5ac334623706.JPG)

**Comment by notoriousbdg** [comment]
It looks like the views are missing.  Try running through the install steps again and ensure that the views have been imported successfully.

**Comment by maljoh** [comment]
Hi

Sorry for not answering i had totally forgot this issue. I will post back when i have tried your solution.

Regards
Rasmus

**Comment by maljoh** [comment]
Hi again

Just tried to run through the installation again and same problem despite it says succesfull import and installation.
Any ideas?
Regards
Rasmus
